version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: app
    depends_on:
      - db

  db:
    image: 'postgres:13'
    container_name: db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
volumes:
  data: